### ISSUE TITLE
Cloning medium/large repo crashes the app

### ISSUE THREAD

**Issue by crutchcorn** [oceanbit-dev/GitShark#41]
While trying to clone the medium-sized repo: https://github.com/unicorn-utterances/unicorn-utterances

I find myself facing the following error:

```
2020-08-06 21:39:40.378 30949-31004/dev.oceanbit.gitshark W/eanbit.gitshar: Throwing OutOfMemoryError "Failed to allocate a 312742456 byte allocation with 50331648 free bytes and 228MB until OOM, target footprint 348090096, growth limit 536870912" (VmSize 7063752 kB)
2020-08-06 21:39:40.384 30949-31004/dev.oceanbit.gitshark E/AndroidRuntime: FATAL EXCEPTION: mqt_js
    Process: dev.oceanbit.gitshark, PID: 30949
    java.lang.OutOfMemoryError: Failed to allocate a 312742456 byte allocation with 50331648 free bytes and 228MB until OOM, target footprint 348090096, growth limit 536870912
        at java.util.Arrays.copyOf(Arrays.java:3257)
        at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:124)
        at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:448)
        at java.lang.StringBuffer.append(StringBuffer.java:270)
        at java.io.StringWriter.write(StringWriter.java:101)
        at android.util.JsonWriter.close(JsonWriter.java:260)
        at android.util.JsonWriter.endObject(JsonWriter.java:231)
        at com.facebook.react.devsupport.JSDebuggerWebSocketClient.executeJSCall(JSDebuggerWebSocketClient.java:123)
        at com.facebook.react.devsupport.WebsocketJavaScriptExecutor.executeJSCall(WebsocketJavaScriptExecutor.java:170)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:26)
        at android.os.Looper.loop(Looper.java:214)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:225)
        at java.lang.Thread.run(Thread.java:919)
2020-08-06 21:39:40.616 30949-30949/dev.oceanbit.gitshark D/ReactNative: ReactInstanceManager.detachViewFromInstance()
2020-08-06 21:44:13.427 30949-30995/dev.oceanbit.gitshark W/System: A resource failed to call response.body().close(). 
```

It's worth mentioning that `android:largeHeap="true"` is already set to `true`

**Comment by crutchcorn** [comment]
It's also worth mentioning that said repo is only 103MB, so where exactly is the other 200MB coming from?

![image](https://user-images.githubusercontent.com/9100169/89610221-d7de8080-d82e-11ea-8c8e-3263c5f5e253.png)
